Add support for Pyret
exercism/tokei pull request #3
Opened 2023-11-01 16:02 UTC by BNAndras

2023-11-01 16:35 UTC, glennj commented
Don't forget to update the README

2023-11-03 11:24 UTC, ErikSchierboom commented
@BNAndras Could you rebase this on the latest `master` of this repo?

2023-11-03 14:54 UTC, glennj requested changes

2023-11-03 14:54 UTC, glennj commented on languages.json
> +      "multi_line_comments": ["#|", "|#"],
```suggestion
      "multi_line_comments": ["#|", "|#"],
      "nested": true,
```
As I discovered with 8th, you have to tell tokei that your language supports nested multiline comments.

2023-11-07 05:23 UTC, BNAndras commented
> @BNAndras Could you rebase this on the latest `master` of this repo?

This branch is also being used in a PR upstream. Will that be a problem for the other PR? I can change branches I think.

2023-11-07 07:16 UTC, ErikSchierboom commented
@BNAndras I would probably just open a new PR for this repo with a different branch.

2023-11-07 22:41 UTC, BNAndras commented
Okay, I opened #10 instead

2023-11-07 22:41 UTC, closed without merging